// <auto-generated />
namespace WebApplication4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class init5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init5));
        
        string IMigrationMetadata.Id
        {
            get { return "201610121929479_init5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
